In [11]:
import pandas as pd
df_question = pd.read_csv("test.csv")
df_question

,id,question,answer,answer_idx,meta_info,option_A,option_B,option_C,option_D,option_E
0,Q0001,A junior orthopaedic surgery resident is compl...,Tell the attending that he cannot fail to disc...,C,step1,Disclose the error to the patient but leave it...,Disclose the error to the patient and put it i...,Tell the attending that he cannot fail to disc...,Report the physician to the ethics committee,Refuse to dictate the operative report
1,Q0002,A 67-year-old man with transitional cell carci...,Cross-linking of DNA,E,step1,Inhibition of thymidine synthesis,Inhibition of proteasome,Hyperstabilization of microtubules,Generation of free radicals,Cross-linking of DNA
2,Q0003,Two weeks after undergoing an emergency cardia...,Cholesterol embolization,C,step2&3,Renal papillary necrosis,Allergic interstitial nephritis,Cholesterol embolization,Eosinophilic granulomatosis with polyangiitis,Polyarteritis nodosa
3,Q0004,A 39-year-old woman is brought to the emergenc...,"Lactose-fermenting, gram-negative rods forming...",D,step1,"Coagulase-positive, gram-positive cocci formin...","Encapsulated, gram-negative coccobacilli formi...","Spore-forming, gram-positive bacilli forming y...","Lactose-fermenting, gram-negative rods forming...","Gamma-hemolytic, gram-positive cocci forming g..."
4,Q0005,A 35-year-old man comes to the physician becau...,Ketotifen eye drops,B,step2&3,Erythromycin ointment,Ketotifen eye drops,Warm compresses,Fluorometholone eye drops,Latanoprost eye drops
...,...,...,...,...,...,...,...,...,...,...
1268,Q1269,A 39-year-old woman presents to the clinic for...,Thyroid-stimulating hormone (TSH),E,step2&3,Erythropoietin,Glucose,Triiodothyronine (T3),Thyroxine (T4),Thyroid-stimulating hormone (TSH)
1269,Q1270,A 38-year-old woman comes to the physician bec...,Medication abuse,E,step2&3,Celiac disease,Carcinoid tumor,VIPoma,Irritable bowel syndrome,Medication abuse
1270,Q1271,A 21-year-old college student comes to the phy...,Stop evening exercise,C,step2&3,Trial of diphenhydramine,Complete caffeine cessation,Stop evening exercise,Alcoholic beverage prior to bedtime,Scheduled afternoon naps
1271,Q1272,A 19-year-old man is brought to the physician ...,Schizotypal personality disorder,C,step2&3,Social anxiety disorder,Avoidant personality disorder,Schizotypal personality disorder,Paranoid personality disorder,Schizophrenia
1272,Q1273,A 79-year-old man presents to the office due t...,Chronic obstructive pulmonary disease (COPD),C,step1,Asthma,Lymphangioleiomyomatosis,Chronic obstructive pulmonary disease (COPD),Bronchiectasis,Heart failure

# GPT 5.4

In [12]:
df_54 = pd.read_csv("./run2 gpt all/run2_gpt5_4.csv")
df_54

,id,run2_initial_answer,run2_initial_confidence,run2_answer,run2_confidence
0,Q0001,C,83,B,94
1,Q0002,E,99,E,99
2,Q0003,C,99,C,99
3,Q0004,D,88,D,89
4,Q0005,B,98,B,99
...,...,...,...,...,...
1268,Q1269,E,98,E,99
1269,Q1270,E,98,E,99
1270,Q1271,B,81,B,86
1271,Q1272,C,97,C,99
1272,Q1273,C,99,C,99

In [13]:
df_54 = df_54.merge(
  df_question,
  on="id",
  how="left"
)

df_54

,id,run2_initial_answer,run2_initial_confidence,run2_answer,run2_confidence,question,answer,answer_idx,meta_info,option_A,option_B,option_C,option_D,option_E
0,Q0001,C,83,B,94,A junior orthopaedic surgery resident is compl...,Tell the attending that he cannot fail to disc...,C,step1,Disclose the error to the patient but leave it...,Disclose the error to the patient and put it i...,Tell the attending that he cannot fail to disc...,Report the physician to the ethics committee,Refuse to dictate the operative report
1,Q0002,E,99,E,99,A 67-year-old man with transitional cell carci...,Cross-linking of DNA,E,step1,Inhibition of thymidine synthesis,Inhibition of proteasome,Hyperstabilization of microtubules,Generation of free radicals,Cross-linking of DNA
2,Q0003,C,99,C,99,Two weeks after undergoing an emergency cardia...,Cholesterol embolization,C,step2&3,Renal papillary necrosis,Allergic interstitial nephritis,Cholesterol embolization,Eosinophilic granulomatosis with polyangiitis,Polyarteritis nodosa
3,Q0004,D,88,D,89,A 39-year-old woman is brought to the emergenc...,"Lactose-fermenting, gram-negative rods forming...",D,step1,"Coagulase-positive, gram-positive cocci formin...","Encapsulated, gram-negative coccobacilli formi...","Spore-forming, gram-positive bacilli forming y...","Lactose-fermenting, gram-negative rods forming...","Gamma-hemolytic, gram-positive cocci forming g..."
4,Q0005,B,98,B,99,A 35-year-old man comes to the physician becau...,Ketotifen eye drops,B,step2&3,Erythromycin ointment,Ketotifen eye drops,Warm compresses,Fluorometholone eye drops,Latanoprost eye drops
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1268,Q1269,E,98,E,99,A 39-year-old woman presents to the clinic for...,Thyroid-stimulating hormone (TSH),E,step2&3,Erythropoietin,Glucose,Triiodothyronine (T3),Thyroxine (T4),Thyroid-stimulating hormone (TSH)
1269,Q1270,E,98,E,99,A 38-year-old woman comes to the physician bec...,Medication abuse,E,step2&3,Celiac disease,Carcinoid tumor,VIPoma,Irritable bowel syndrome,Medication abuse
1270,Q1271,B,81,B,86,A 21-year-old college student comes to the phy...,Stop evening exercise,C,step2&3,Trial of diphenhydramine,Complete caffeine cessation,Stop evening exercise,Alcoholic beverage prior to bedtime,Scheduled afternoon naps
1271,Q1272,C,97,C,99,A 19-year-old man is brought to the physician ...,Schizotypal personality disorder,C,step2&3,Social anxiety disorder,Avoidant personality disorder,Schizotypal personality disorder,Paranoid personality disorder,Schizophrenia
1272,Q1273,C,99,C,99,A 79-year-old man presents to the office due t...,Chronic obstructive pulmonary disease (COPD),C,step1,Asthma,Lymphangioleiomyomatosis,Chronic obstructive pulmonary disease (COPD),Bronchiectasis,Heart failure

# Basic Information
- acc
- confidence (mean +- std)
- confidence if correct (mean +- std)
- confidence if incorrect (mean +- std)
- calibration gap (pp)
- ECE
- Brier Score

Overall, step1, step2&3

In [14]:
import pandas as pd
import numpy as np

df = df_54.copy()

df = df.dropna(
  subset=[
    "run2_initial_answer",
    "run2_initial_confidence",
    "run2_answer",
    "run2_confidence",
    "answer_idx",
    "meta_info"
  ]
).copy()

df["run2_initial_answer"] = df["run2_initial_answer"].astype(str).str.strip()
df["run2_answer"] = df["run2_answer"].astype(str).str.strip()
df["answer_idx"] = df["answer_idx"].astype(str).str.strip()

df["run2_initial_confidence"] = pd.to_numeric(
  df["run2_initial_confidence"],
  errors="coerce"
)

df["run2_confidence"] = pd.to_numeric(
  df["run2_confidence"],
  errors="coerce"
)

df = df.dropna(
  subset=[
    "run2_initial_confidence",
    "run2_confidence"
  ]
).copy()

df["meta_subset"] = np.where(
  df["meta_info"].astype(str).str.lower().str.contains("step1"),
  "Step 1",
  "Step 2 & 3"
)

df["initial_correct"] = df["run2_initial_answer"].eq(df["answer_idx"])
df["final_correct"] = df["run2_answer"].eq(df["answer_idx"])


def ece_score(correct, confidence, n_bins=10):
  correct = np.asarray(correct).astype(int)
  confidence = np.asarray(confidence).astype(float)

  bins = np.linspace(0, 1, n_bins + 1)
  ece = 0

  for i in range(n_bins):
    lower = bins[i]
    upper = bins[i + 1]

    if i == 0:
      mask = (confidence >= lower) & (confidence <= upper)
    else:
      mask = (confidence > lower) & (confidence <= upper)

    if mask.sum() > 0:
      bin_acc = correct[mask].mean()
      bin_conf = confidence[mask].mean()
      ece += (mask.sum() / len(confidence)) * abs(bin_acc - bin_conf)

  return ece


def mean_sd_string(series):
  if len(series) == 0:
    return "NA"

  mean_value = series.mean()
  sd_value = series.std(ddof=1)

  if pd.isna(sd_value):
    return f"{mean_value:.2f} ± NA"

  return f"{mean_value:.2f} ± {sd_value:.2f}"


def summarize_basic(data, conf_col, correct_col, label):
  out = []

  subsets = [
    ("Overall", data),
    ("Step 1", data[data["meta_subset"].eq("Step 1")]),
    ("Step 2 & 3", data[data["meta_subset"].eq("Step 2 & 3")])
  ]

  for subset_name, d in subsets:
    if len(d) == 0:
      continue

    correct = d[correct_col].astype(int)
    conf = d[conf_col].astype(float)
    conf_prob = conf / 100

    acc = correct.mean() * 100
    mean_conf = conf.mean()

    d_correct = d[d[correct_col]]
    d_incorrect = d[~d[correct_col]]

    calibration_gap = mean_conf - acc
    ece = ece_score(correct, conf_prob, n_bins=10) * 100
    brier = np.mean((conf_prob - correct) ** 2)

    out.append({
      "Response": label,
      "Subset": subset_name,
      "N": len(d),
      "Accuracy (%)": round(acc, 2),
      "Confidence, mean ± SD (%)": mean_sd_string(conf),
      "Confidence if correct, mean ± SD (%)": mean_sd_string(d_correct[conf_col]),
      "Confidence if incorrect, mean ± SD (%)": mean_sd_string(d_incorrect[conf_col]),
      "Calibration gap (pp)": round(calibration_gap, 2),
      "ECE (pp)": round(ece, 2),
      "Brier score": round(brier, 2)
    })

  return pd.DataFrame(out)


table_initial = summarize_basic(
  data=df,
  conf_col="run2_initial_confidence",
  correct_col="initial_correct",
  label="Baseline"
)

table_final = summarize_basic(
  data=df,
  conf_col="run2_confidence",
  correct_col="final_correct",
  label="Post-reflection"
)

basic_table = pd.concat(
  [
    table_initial,
    table_final
  ],
  ignore_index=True
)

basic_table = basic_table[
  [
    "Response",
    "Subset",
    "N",
    "Accuracy (%)",
    "Confidence, mean ± SD (%)",
    "Confidence if correct, mean ± SD (%)",
    "Confidence if incorrect, mean ± SD (%)",
    "Calibration gap (pp)",
    "ECE (pp)",
    "Brier score"
  ]
]

basic_table

,Response,Subset,N,Accuracy (%),"Confidence, mean ± SD (%)","Confidence if correct, mean ± SD (%)","Confidence if incorrect, mean ± SD (%)",Calibration gap (pp),ECE (pp),Brier score
0,Baseline,Overall,1273,90.73,95.72 ± 4.67,96.27 ± 3.88,90.39 ± 7.55,4.99,4.99,0.08
1,Baseline,Step 1,679,90.72,95.90 ± 4.85,96.51 ± 3.73,89.92 ± 8.86,5.18,5.18,0.08
2,Baseline,Step 2 & 3,594,90.74,95.52 ± 4.45,95.99 ± 4.02,90.93 ± 5.74,4.78,4.89,0.08
3,Post-reflection,Overall,1273,90.49,96.81 ± 4.64,97.35 ± 3.85,91.69 ± 7.52,6.31,6.38,0.08
4,Post-reflection,Step 1,679,90.43,96.99 ± 4.65,97.60 ± 3.59,91.31 ± 8.36,6.57,6.69,0.08
5,Post-reflection,Step 2 & 3,594,90.57,96.60 ± 4.62,97.06 ± 4.12,92.14 ± 6.45,6.02,6.44,0.08

In [16]:
import pandas as pd
import numpy as np
from scipy.stats import binom, chi2

df = df_54.copy()

df = df.dropna(
  subset=[
    "run2_initial_answer",
    "run2_initial_confidence",
    "run2_answer",
    "run2_confidence",
    "answer_idx",
    "meta_info"
  ]
).copy()

df["run2_initial_answer"] = df["run2_initial_answer"].astype(str).str.strip()
df["run2_answer"] = df["run2_answer"].astype(str).str.strip()
df["answer_idx"] = df["answer_idx"].astype(str).str.strip()

df["run2_initial_confidence"] = pd.to_numeric(
  df["run2_initial_confidence"],
  errors="coerce"
)

df["run2_confidence"] = pd.to_numeric(
  df["run2_confidence"],
  errors="coerce"
)

df = df.dropna(
  subset=[
    "run2_initial_confidence",
    "run2_confidence"
  ]
).copy()

df["meta_subset"] = np.where(
  df["meta_info"].astype(str).str.lower().str.contains("step1"),
  "Step 1",
  "Step 2 & 3"
)

df["initial_correct"] = df["run2_initial_answer"].eq(df["answer_idx"])
df["final_correct"] = df["run2_answer"].eq(df["answer_idx"])

df["answer_revised"] = df["run2_initial_answer"].ne(df["run2_answer"])

df["correct_to_incorrect"] = (
  df["initial_correct"].eq(True) &
  df["final_correct"].eq(False)
)

df["incorrect_to_correct"] = (
  df["initial_correct"].eq(False) &
  df["final_correct"].eq(True)
)


def mcnemar_pvalue(b, c, continuity_correction=False):
  check_valid = lambda n: isinstance(n, int) or (isinstance(n, float) and n.is_integer())

  if not all(map(check_valid, [b, c])):
    raise ValueError("b and c must be integers.")

  b = int(b)
  c = int(c)

  if b < 0 or c < 0:
    raise ValueError("b and c must be non-negative.")

  total_discordant = b + c

  if total_discordant == 0:
    return np.nan

  n_min, n_max = sorted([b, c])
  corr = int(continuity_correction)

  if total_discordant < 25:
    pvalue = (
      2 * binom.cdf(n_min, total_discordant, 0.5)
      - binom.pmf(n_min, total_discordant, 0.5)
    )
  else:
    chi2_statistic = (abs(n_min - n_max) - corr) ** 2 / total_discordant
    pvalue = chi2.sf(chi2_statistic, 1)

  return pvalue


def summarize_post_reflection(data, model_name="GPT-5.2"):
  out = []

  subsets = [
    ("Overall", data),
    ("Step 1", data[data["meta_subset"].eq("Step 1")]),
    ("Step 2 & 3", data[data["meta_subset"].eq("Step 2 & 3")])
  ]

  for subset_name, d in subsets:
    if len(d) == 0:
      continue

    n = len(d)

    baseline_acc = d["initial_correct"].mean() * 100
    post_acc = d["final_correct"].mean() * 100
    delta_acc = post_acc - baseline_acc

    revision_rate = d["answer_revised"].mean() * 100

    correct_to_incorrect_n = int(d["correct_to_incorrect"].sum())
    incorrect_to_correct_n = int(d["incorrect_to_correct"].sum())

    correct_to_incorrect_pct = correct_to_incorrect_n / n * 100
    incorrect_to_correct_pct = incorrect_to_correct_n / n * 100

    mcnemar_p = mcnemar_pvalue(
      correct_to_incorrect_n,
      incorrect_to_correct_n,
      continuity_correction=False
    )

    out.append({
      "Subset (N)": f"{subset_name} ({n})",
      "Model": model_name,
      "Baseline accuracy (%)": round(baseline_acc, 2),
      "Post-reflection accuracy (%)": round(post_acc, 2),
      "Δ accuracy (pp)": round(delta_acc, 2),
      "Revision rate (%)": round(revision_rate, 2),
      "Correct→Incorrect (%)": round(correct_to_incorrect_pct, 2),
      "Incorrect→Correct (%)": round(incorrect_to_correct_pct, 2),
      "McNemar p-value": round(mcnemar_p, 4) if not pd.isna(mcnemar_p) else np.nan
    })

  return pd.DataFrame(out)


post_reflection_table = summarize_post_reflection(
  data=df,
  model_name="GPT-5.4"
)

post_reflection_table

,Subset (N),Model,Baseline accuracy (%),Post-reflection accuracy (%),Δ accuracy (pp),Revision rate (%),Correct→Incorrect (%),Incorrect→Correct (%),McNemar p-value
0,Overall (1273),GPT-5.4,90.73,90.49,-0.24,0.79,0.47,0.24,0.3437
1,Step 1 (679),GPT-5.4,90.72,90.43,-0.29,1.33,0.74,0.44,0.5078
2,Step 2 & 3 (594),GPT-5.4,90.74,90.57,-0.17,0.17,0.17,0.00,0.5000